(defvar *num* nil)
(defun print42 ()
  (dolist (i (reverse *num*))
    (if (eql i 42)
	(return)
	(format t "~&~S~%" i))))
(defun read42 ()
  (loop (let ((x (read)))
     (if (eql x 42)
	 (return)
	 (push x *num*)))))
(read42)
(print42)
